= Documentation - How it is made...

:toc: preamble

This is the documentation for the AWS backup script.

== Use Case 

The following diagram 

[text]
....

│                   ┌─────────────────────┐
├─ not_synched    ◄─┤ This folder is      │
│                   │ excluded            │
│                   └─────────────────────┘
│
│                   ┌─────────────────────────────────┐
└─ synched        ◄─┤ This folder and the sub folders │
    │               │  will be synched to AWS S3      │
    │               └─────────────────────────────────┘
    ├─ backup1
    ├─ backup2
    └─ backup3
  
....

== Links

* https://www.middlewareinventory.com/blog/aws-s3-sync-example/[Tutorial for synching a folder with S3 and AWS CLI]
* https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html[AWS docs concerning AWS CLI configuration files]
* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/sync.html[AWS docs concerning AWS CLI synch]


== rsync

https://unix.stackexchange.com/questions/203846/how-to-sync-two-folders-with-command-line-tools

This puts folder A into folder B:

rsync -avu --delete "/home/user/A" "/home/user/B"  
If you want the contents of folders A and B to be the same, put /home/user/A/ (with the slash) as the source. This takes not the folder A but all of it's content and puts it into folder B. Like this:


rsync -avc --delete "test.a/"  "test.b"

-a Do the sync preserving all filesystem attributes
-v run verbosely
-c  skip based on checksum, not mod-time & size
--delete delete the files in target folder that do not exist in the source

-u only copy files with a newer modification time (or size difference if the times are equal)

Manpage: https://download.samba.org/pub/rsync/rsync.html


=== cygnwin

rsync -avc "/cygdrive/c/dev/test.a/"  "/cygdrive/t/ch00bhe/test.b"


== Configure the AWS CLI

You can specify a non-default location for the files by setting the AWS_CONFIG_FILE and AWS_SHARED_CREDENTIALS_FILE environment variables to another local path.

[bash]
....

$ export AWS_CONFIG_FILE="/mnt/veracrypt/aws_cli/config"
$ export AWS_SHARED_CREDENTIALS_FILE="/mnt/veracrypt/aws_cli/credentials"

....

The configuration and the credentials for the backup are expected in a profile with the name "backup".


[bash]
....

$ aws s3 synch --profile backup

....

== To-Do

. https://markphelps.me/posts/writing-tests-for-your-database-code-in-go/
* Implement the storage test cases 
* Storage config in "measurement" initialize it with test db 
* Using the test config for test_db.go
* remove the models package

. Create the service layer with the business logic
* ID creation
* Validation 

. Create the API layer with gin -> main.go
* Add Swagger annotations

. Add the static content 

. Create an cmd with logging, ...
